name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.15.47.151
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/almeida-inteligencia-site
            git pull
            /usr/local/bin/docker-compose-v2 up -d --build
